import { LightningElement } from 'lwc';
import resourceTest from '@salesforce/resourceUrl/productIconography';
export default class TestZipFileAccessingAndShow extends LightningElement {
    p_0_10V_Dimming = resourceTest + '/0-10V Dimming.png';
    p_1_10V_Dimming = resourceTest + '/1-10V Dimming.png';
    p_3_in_1_Dimming = resourceTest + '/3 in 1 Dimming.png';
    p_14_Day_Returns = resourceTest + '/14 Day Returns.png';
    p_A_Energy_Rating = resourceTest + '/A Energy Rating.png';
    p_A_Plus_Energy_Rating = resourceTest + '/A+ Energy Rating.png';
    p_A_Plus_plus_Energy_Rating = resourceTest + '/A++ Energy Rating.png';
    p_A_Plus_plus_plus_Energy_Rating = resourceTest + '/A+++ Energy Rating.png';
    p_Anti_Glare = resourceTest + '/Anti Glare.png';
    p_B_Energy_Rating = resourceTest + '/B Energy Rating.png';
    p_C_Energy_Rating = resourceTest + '/C Energy Rating.png';
    p_Corridor_Function = resourceTest + '/Corridor Function.png';
    p_D_Energy_Rating = resourceTest + '/D Energy Rating.png';
    p_DALI_Self_Test = resourceTest + '/DALI Self Test.png';
    p_DALI = resourceTest + '/DALI.png';
    p_DALI_2 = resourceTest + '/DALI-2.png';
    p_Daylight_Harvesting = resourceTest + '/Daylight Harvesting.png';
    p_Design_Service = resourceTest + '/Design Service.png';
    p_Diffused_on_Board = resourceTest + '/Diffused on Board.png';
    p_Dimmable = resourceTest + '/Dimmable.png';
    p_Dual_Zone_Microwave_Sensor = resourceTest + '/Dual Zone Microwave Sensor.png';
    p_Dusk_to_Dawn = resourceTest + '/Dusk to Dawn.png';
    p_Emergency_Self_Test = resourceTest + '/Emergency Self Test.png';
    p_Emergency = resourceTest + '/Emergency.png';
    p_EOL = resourceTest + '/EOL.png';
    p_Fast_Delivery = resourceTest + '/Fast Delivery.png';
    p_Flicker_Free = resourceTest + '/Flicker Free.png';
    p_Freezer_Functionality = resourceTest + '/Freezer Functionality.png';
    p_High_Inrush_Current = resourceTest + '/High Inrush Current.png';
    p_IK_Rating = resourceTest + '/IK Rating.png';
    p_In_Development = resourceTest + '/In Development.png';
    p_IP_Rating = resourceTest + '/IP Rating.png';
    p_Low_Profile = resourceTest + '/Low Profile.png';
    p_Low_Temperature = resourceTest + '/Low Temperature.png';
    p_Microwave_Sensor = resourceTest + '/Microwave Sensor.png';
    p_Motion_Sensor = resourceTest + '/Motion Sensor.png';
    p_New = resourceTest + '/New.png';
    p_NRND = resourceTest + '/NRND.png';
    p_On_Site_Survey = resourceTest + '/On Site Survey.png';
    p_PIR = resourceTest + '/PIR.png';
    p_Reviews = resourceTest + '/Reviews.png';
    p_Special_Order_Part = resourceTest + '/Special Order Part.png';
    p_Trade_Account = resourceTest + '/Trade Account.png';
    p_UGR = resourceTest + '/UGR.png';
}